version: '3.0'
services:
  mqseries:
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    hostname: mq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
    container_name: mqserver
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - "./20-config.mqsc:/etc/mqm/20-config.mqsc"
      - "qm1data:/mnt/mqm"
  message-flow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: message-flow
    restart: always
    environment:
      MQ_HOSTNAME: "mqseries"
    depends_on:
      - mqseries
volumes:
  qm1data: 



